name: Access Issue Information
on:
  issues:
    types: [opened, reopened, labeled]
env: 
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPOSITORY: ${{ github.repository }}
  ISSUE_NUMBER: ${{ github.event.issue.number }}
  CHAT_GPT_API: ${{ secrets.OPENAI_API_KEY }}
  ISSUE_LABELS: ${{ join(github.event.issue.labels.*.name, ', ') }}
jobs:
  asking_chat_bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Set permissions X
        run: chmod +x scripts/script.sh
        
      - name: Creating yml
        run: echo ${ISSUE_LABELS}

      - if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
        run: echo "Great!"
        
      - name: Checking label
        run: echo ${REPOSITORY}
      


              # - id: Check_bot
      #  run: if contains(github.event.issue.labels.*.name, 'autocoder-bot'); then exit 0; else exit 1; fi
        
      # - if: ${{ always() }}
      #  run: echo "YES!"
        

        #  echo ${REPOSITORY}
        #  echo ${REPOSITORY}

          # echo "GITHUB_TOKEN: ${GITHUB_TOKEN}"
          # echo "Issue Number: ${ISSUE_NUMBER}"
          # echo "CHATGPT_TOKEN: ${CHAT_GPT_API}"
        # if: contains(github.event.issue.labels.*.name, 'autocoder-bot')     
                  # ISSUE_TITLE: ${{ github.event.issue.title }}
          # ISSUE_BODY: ${{ github.event.issue.body }}
          # ISSUE_LABELS: ${{ join(github.event.issue.labels.*.name, ', ') }}
          # LOGIN: ${{ join(github.event.issue.assignees.*.login, ', '), ', ') }}
          
          
