name: Workflow Name
on: 
  [push]
  
jobs:
  job_name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        run: echo "Hello"

      - name: Greeting Message
        run: echo ", world"
