name: Access Issue Information
on:
  issues:
    types: [opened, reopened]
  
jobs:
  job_name:
    env: 
      ISSUE_NUMBER: ${{ github.event.issue.number }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Greeting Message
        run: echo "Issue arrived!"
      - name: Printing data
        run: |
          echo "Issue Number: ${ISSUE_NUMBER}"
